nahan/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 10:15:12

from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config


mail = Mail()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .user import user as user_blueprint
    app.register_blueprint(user_blueprint, url_prefix='/user')
    from .voice import voice as voice_blueprint
    app.register_blueprint(voice_blueprint)
    from .brother import brother as brother_blueprint
    app.register_blueprint(brother_blueprint)
    return app

nahan/brother/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-18 21:33:24

from flask import Blueprint
brother = Blueprint('brother', __name__)
from . import views

nahan/brother/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-09-08 18:06:32

from flask import render_template, redirect, request, url_for, abort, current_app, jsonify
from flask_login import login_user, logout_user, current_user
from flask_babel import gettext
from functools import wraps
from flask_paginate import Pagination
from ..util import natural_time
from ..models import User, Topic, Node, Comment, TopicAppend
from . import brother
from .. import db


def superuser_login(func):
    @wraps(func)
    def wrap(*args, **kwargs):
        if current_user.is_authenticated and current_user.is_superuser:
            return func(*args, **kwargs)
        else:
            return redirect(url_for('brother.auth', next=request.url))
    return wrap


@brother.route("/admin/", methods=['GET', 'POST'])
def auth():
    if request.method == 'GET':
        if current_user.is_authenticated and current_user.is_superuser:
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        return render_template("brother/auth.html", form=None)
    elif request.method == 'POST':
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()
        if u and u.verify_password(_form['password']) and u.is_superuser:
            login_user(u)
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        else:
            message = gettext('Invalid username or password.')
            return render_template('brother/auth.html', form=_form, message=message)


@brother.route("/admin/signout/")
@superuser_login
def signout():
    logout_user()
    return redirect(url_for('brother.auth'))


@brother.route("/admin/topics/")
@superuser_login
def topic_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/topic.html', title=gettext('Normal Topics'))
        elif classify == 'deleted':
            return render_template('brother/topic_deleted.html', title=gettext('Deleted Topics'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/comments/")
@superuser_login
def comment_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/comment.html', title=gettext('Normal Comments'))
        elif classify == 'deleted':
            return render_template('brother/comment_deleted.html', title=gettext('Deleted Comments'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/nodes/")
@superuser_login
def node_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/node.html', title=gettext('Normal Nodes'))
        elif classify == 'deleted':
            return render_template('brother/node_deleted.html', title=gettext('Deleted Nodes'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/users/")
@superuser_login
def user_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/user.html', title=gettext('Normal Users'))
        elif classify == 'deleted':
            return render_template('brother/user_deleted.html', title=gettext('Blacklist Users'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/topic/<int:tid>/")
@superuser_login
def topic_more(tid):
    """ Delete part or all of one topic.

    Can delete either one or more comment, appendix or the whole topic.
    """
    t = Topic.query.filter_by(id=tid).first_or_404()
    if request.method == 'GET':
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        all_comments = t.extract_comments()
        comments = all_comments[offset:offset + per_page]
        pagination = Pagination(page=page, total=len(all_comments),
                                per_page=per_page,
                                record_name='comments',
                                CSS_FRAMEWORK='bootstrap',
                                bs_version=3)

        return render_template('brother/topic_more.html',
                               title=gettext('More About Topic'),
                               topic=t,
                               comments=comments,
                               pagination=pagination)
    else:
        abort(404)


@brother.route("/admin/node/<int:nid>/", methods=['GET', 'POST'])
@superuser_login
def node_more(nid):
    """ Update the title and description of node despite of node is deleted or not.
    """
    n = Node.query.filter_by(id=nid).first_or_404()
    if request.method == 'GET':
        return render_template('brother/node_more.html',
                               title=gettext('More About Node'),
                               node=n)
    elif request.method == 'POST':
        n.title = request.form['title']
        n.description = request.form['description']
        db.session.commit()
        return redirect(url_for('brother.node_manage', classify="normal"))
    else:
        abort(404)


@brother.route("/admin/user/<int:uid>/")
@superuser_login
def user_more(uid):
    content = request.args['content']
    if content not in ['Topic', 'Comment']:
        abort(404)

    if request.method == 'GET':
        u = User.query.filter_by(id=uid).first_or_404()
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        if content == 'Topic':
            all_topics = u.extract_topics()
            topics = all_topics[offset:offset + per_page]
            pagination_topic = Pagination(page=page, total=len(all_topics),
                                          per_page=per_page,
                                          record_name='topics',
                                          CSS_FRAMEWORK='bootstrap',
                                          bs_version=3)
            return render_template('brother/user_more_topic.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   topics=topics,
                                   pagination_topic=pagination_topic)
        else:
            all_comments = u.extract_comments()
            comments = all_comments[offset:offset + per_page]
            pagination_comment = Pagination(page=page, total=len(all_comments),
                                            per_page=per_page,
                                            record_name='comments',
                                            CSS_FRAMEWORK='bootstrap',
                                            bs_version=3)
            return render_template('brother/user_more_comment.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   comments=comments,
                                   pagination_comment=pagination_comment)
    else:
        abort(404)


@brother.route("/admin/topics/list/")
@superuser_login
def topic_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'reply_count', 'username', 'node_title']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    topics = Topic.query.filter_by(deleted=status).all()
    map(lambda x: setattr(x, 'username', x.user().username), topics)
    map(lambda x: setattr(x, 'node_title', x.node().title), topics)

    # Filter the topic according to the keywords.
    key = request.args.get('sSearch')
    if key:
        topics = list(filter(lambda x: (key == str(x.id) or key == str(x.reply_count) or key in x.title or
                                        key in x.username or key in x.node_title), topics))

    # Sort the data according to specified columns.
    topics.sort(key=lambda x: getattr(x, fields[order_field]), reverse=False if order_dir == 'asc' else True)

    # Put data together to response.
    data = dict()
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(topics)
    data['iTotalRecords'] = Topic.query.count()

    topics = topics[start:start + length]
    map(lambda x: setattr(x, 'more',
                          '<a href="%s" class="label label-success">%s</a>' %
                          (url_for('brother.topic_more', tid=x.id), gettext('more'))), topics)
    data['aaData'] = [[t.id, t.title, t.reply_count, t.username, t.node_title, t.more] for t in topics]

    return jsonify(**data)


@brother.route("/admin/nodes/list/")
@superuser_login
def node_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'description', 'count']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    nodes = Node.query.filter_by(deleted=status).all()
    # Filter the users according to the keywords.
    key = request.args.get('sSearch')

    map(lambda x: setattr(x, 'count', 0 if not x.topics else len(x.topics.split(","))), nodes)
    if key:
        nodes = list(filter(lambda x: (key == str(x.id) or key in x.title or

nahan/user/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-06-30 21:55:44

from flask import Blueprint
user = Blueprint('user', __name__)
from . import views

nahan/voice/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 09:44:05


from flask import Blueprint
voice = Blueprint('voice', __name__)
from . import views

nahan/templates/brother/auth.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=360, initial-scale=0.75 user-scalable=no">
        <title>{{ _('Administrator sign in') }}</title>

        <!-- Bootstrap -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    </head>
    <body>
    <div class="panel panel-default col-md-6 col-md-offset-3" style="margin-top:5em">

        <form class="panel-body" role="form" method="post" action="{{ url_for('brother.auth', next=request.args.get('next')) }}">
            <h2 class="text-center" style="margin-bottom:1em"> {{ _('Administrator Sign In')}} </h2>
            {% if message %}
            <div class="messages"> <p class="text-danger"> {{ message }} </p></div>
            {% endif %}
            <div class="form-group ">
                <label for="email"> {{ _('email') }} </label>
                <input class="form-control" id="email" name="email" placeholder=example@gmail.com type="text", value="{{ form.email}}">
            </div>

            <div class="form-group ">
                <label for="password">{{_('password') }}</label>
                <input class="form-control" id="password" name="password" type="password", value="{{ form.password}}">
            </div>

            <div class="form-group">
                <button class="btn btn-default btn-success pull-right">
                    {{ _('sign in') }}
                </button>
            </div>
        </form>
    </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

nahan/templates/brother/comment.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Normal Comments') }}
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-default table-bordered display" cellspacing="0" id="normal">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ _('Content') }}</th>
                        <th>{{ _('Username') }}</th>
                        <th>{{ _('Topic') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <p></p>
        <a class="btn btn-danger" id="bulk-delete">{{ _('Delete Selected Comment') }}</a>
    </div>
</div>
{% endblock %}

{% block footer_ext %}
<script>
$(document).ready(
    function() {
        $('#normal').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json"
            },
            bProcessing: true,
            bServerSide: true,
            bPaginate: true,
            sAjaxSource: "{{ url_for('brother.comment_table_list', deleted=False) }}",
            sDom: "<'row'<'col-sm-4'l><'col-sm-8 text-right'f>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6 text-right'p><'col-sm-0 text-right'T>>",
            oTableTools: {"sRowSelect": "multi",
                            "aButtons": []},
        });
    });


$(document).ready(function() {
    var table = $('#normal').DataTable();

    $('#normal tbody').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
    } );
} );

function selected_id(){
    selected_rows = $('tr.selected');
    ids = []
    selected_rows.each(
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
        )
    return ids.toString()
}

$(document).ready(
        function(){
            $('#bulk-delete').click(
                function(){
                    $.get('{{ url_for("brother.comment_bulk_process", process="del", next=request.url) }}', {'ids': selected_id()});
                    location.reload();
                }
                );
        }
        );
</script>
{% endblock %}

nahan/templates/brother/node.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Normal Nodes') }}
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-default table-bordered display" cellspacing="0" id="normal">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ _('Title') }}</th>
                        <th>{{ _('Description') }}</th>
                        <th>{{ _('Topic Count') }}</th>
                        <th>{{ _('More') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <p></p>
        <a class="btn btn-danger" id="bulk-delete">{{ _('Delete Selected Nodes') }}</a>
    </div>
</div>
{% endblock %}

{% block footer_ext %}
<script>
$(document).ready(
    function() {
        $('#normal').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json"
            },
            bProcessing: true,
            bServerSide: true,
            bPaginate: true,
            sAjaxSource: "{{ url_for('brother.node_table_list', deleted=False) }}",
            aoColumnDefs: [{ 'bSortable': false, 'aTargets': [ -1 ] }],
            sDom: "<'row'<'col-sm-4'l><'col-sm-8 text-right'f>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6 text-right'p><'col-sm-0 text-right'T>>",
            oTableTools: {"sRowSelect": "multi",
                            "aButtons": []},
        });
    });


$(document).ready(function() {
    var table = $('#normal').DataTable();

    $('#normal tbody').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
    } );
} );

function selected_id(){
    selected_rows = $('tr.selected');
    ids = []
    selected_rows.each(
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
        )
    return ids.toString()
}

$(document).ready(
        function(){
            $('#bulk-delete').click(
                function(){
                    $.get('{{ url_for("brother.node_bulk_process", process="del") }}', {'ids': selected_id()});
                    location.reload();
                }
                );
        }
        );
</script>
{% endblock %}

nahan/templates/brother/node_deleted.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Deleted Nodes') }}
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-default table-bordered display" cellspacing="0" id="normal">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ _('Title') }}</th>
                        <th>{{ _('Description') }}</th>
                        <th>{{ _('Topic Count') }}</th>
                        <th>{{ _('More') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <p></p>
        <a class="btn btn-danger" id="bulk-delete">{{ _('Active Selected Nodes') }}</a>
    </div>
</div>
{% endblock %}

{% block footer_ext %}
<script>
$(document).ready(
    function() {
        $('#normal').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json"
            },
            bProcessing: true,
            bServerSide: true,
            bPaginate: true,
            sAjaxSource: "{{ url_for('brother.node_table_list', deleted=True) }}",
            aoColumnDefs: [{ 'bSortable': false, 'aTargets': [ -1 ] }],
            sDom: "<'row'<'col-sm-4'l><'col-sm-8 text-right'f>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6 text-right'p><'col-sm-0 text-right'T>>",
            oTableTools: {"sRowSelect": "multi",
                            "aButtons": []},
        });
    });


$(document).ready(function() {
    var table = $('#normal').DataTable();

    $('#normal tbody').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
    } );
} );

function selected_id(){
    selected_rows = $('tr.selected');
    ids = []
    selected_rows.each(
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
        )
    return ids.toString()
}

$(document).ready(
        function(){
            $('#bulk-delete').click(
                function(){
                    $.get('{{ url_for("brother.node_bulk_process", process="active") }}', {'ids': selected_id()});
                    location.reload();
                }
                );
        }
        );
</script>
{% endblock %}

nahan/templates/brother/node_more.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading" >
        <a href="{{ url_for('brother.node_manage', classify='normal') }}">{{ _('Node Management') }}</a>
        <span> / {{ node.title }}</span>
    </div>
    <div class="panel-body">
    	{% if message %}
		<div class="messages">
			<p class="text-danger">
				{{ message }}
			</p>
		</div>
		{% endif %}

        <form class="form" action="{{ url_for('brother.node_more', nid=node.id) }}" method="post">
            <div class="form-group">
                <label>{{ _('Title') }}</label>
                <input value="{{node.title}}" type="text" class="form-control" id="title" name="title" />
            </div>
            <div class="form-group">
                <label>{{ _('Description') }}</label>
                <textarea class="form-control" id="description" name="description">{{node.description}}</textarea>
            </div>

            <div class="form-submit text-right">
                <button class="btn btn-info" type="submit" id="submit">
                    {{ _('Submit') }}(Ctrl+Enter)
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

nahan/templates/brother/topic.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Normal Topics') }}
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-default table-bordered display" cellspacing="0" id="normal">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ _('Title') }}</th>
                        <th>{{ _('Reply Count') }}</th>
                        <th>{{ _('Username') }}</th>
                        <th>{{ _("Topic's node") }}</th>
                        <th>{{ _('More') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <p></p>
        <a class="btn btn-danger" id="bulk-delete">{{ _('Delete Selected Topic') }}</a>
    </div>
</div>
{% endblock %}

{% block footer_ext %}
<script>
$(document).ready(
    function() {
        $('#normal').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json"
            },
            bProcessing: true,
            bServerSide: true,
            bPaginate: true,
            sAjaxSource: "{{ url_for('brother.topic_table_list', deleted=False) }}",
            aoColumnDefs: [{ 'bSortable': false, 'aTargets': [ -1 ] }],
            sDom: "<'row'<'col-sm-4'l><'col-sm-8 text-right'f>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6 text-right'p><'col-sm-0 text-right'T>>",
            oTableTools: {"sRowSelect": "multi",
                            "aButtons": []},
        });
    });


$(document).ready(function() {
    var table = $('#normal').DataTable();

    $('#normal tbody').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
    } );
} );

function selected_id(){
    selected_rows = $('tr.selected');
    ids = []
    selected_rows.each(
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
        )
    return ids.toString()
}

$(document).ready(
        function(){
            $('#bulk-delete').click(
                function(){
                    $.get('{{ url_for("brother.topic_bulk_process", process="del") }}', {'ids': selected_id()});
                    location.reload();
                }
                );
        }
        );
</script>
{% endblock %}

nahan/templates/brother/topic_deleted.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        {{ _('Deleted Topics') }}
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-default table-bordered display" cellspacing="0" id="blacklist">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{ _('Title') }}</th>
                        <th>{{ _('Reply Count') }}</th>
                        <th>{{ _('Username') }}</th>
                        <th>{{ _("Topic's node") }}</th>
                        <th>{{ _('More') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <p></p>
        <a class="btn btn-danger" id="bulk-add">{{ _('Active Selected Topic Again') }}</a>
    </div>
</div>
{% endblock %}

{% block footer_ext %}
<script>
$(document).ready(
    function() {
        $('#blacklist').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json"
            },
            bProcessing: true,
            bServerSide: true,
            bPaginate: true,
            sAjaxSource: "{{ url_for('brother.topic_table_list', deleted=True) }}",
            aoColumnDefs: [{ 'bSortable': false, 'aTargets': [ -1 ] }],
            sDom: "<'row'<'col-sm-4'l><'col-sm-8 text-right'f>r>" + "t" + "<'row'<'col-sm-6'i><'col-sm-6 text-right'p><'col-sm-0 text-right'T>>",
            oTableTools: {"sRowSelect": "multi",
                            "aButtons": []},
        });
    });


$(document).ready(function() {
    var table = $('#blacklist').DataTable();

    $('#blacklist tbody').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
    } );
} );

function selected_id(){
    selected_rows = $('tr.selected');
    ids = []
    selected_rows.each(
            function(){
                ids.push($(this).context.cells[0].childNodes[0].data);
            }
        )
    return ids.toString()
}

$(document).ready(
        function(){
            $('#bulk-add').click(
                function(){
                    $.get('{{ url_for("brother.topic_bulk_process", process="active") }}', {'ids': selected_id()});
                    location.reload();
                }
                );
        }
        );
</script>
{% endblock %}

nahan/templates/brother/topic_more.html
{% extends 'base_admin.html' %}

{% block main %}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-10">
                <h3 class="list-post-title-in-topic"> {{ topic.title }} </h3>
            </div>
            <div class="col-md-2">
                {% if not topic.deleted %}
                <a type="button" class="btn btn-danger" href="{{ url_for('brother.topic_process', tid = topic.id, process='del') }}"> {{ _('Delete Topic') }}</a>
                {% elif topic.deleted and topic.topic_deleted %}
                <a type="button" class="btn btn-success" href="{{ url_for('brother.topic_process', tid = topic.id, process='active') }}"> {{ _('Activate Topic') }}</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="panel-body">
        {{ topic.content_rendered | safe}}
    </div>
    {% if topic.appends %}
    <ul class="list-group" id="append">
        {% for a in topic.extract_appends() %}
            {% if a.deleted and not a.append_deleted %}
            <div class="list-group-item list-topic-item blocked">
                <div class="glyphicon glyphicon-ban-circle fa-3x watermark"></div>
            {% else %}
            <div class="list-group-item list-topic-item">
            {% endif %}
                <p class="appendix-meta">
                    {{ _('The ')}}{{ loop.index }} {{ _('appendix') }} {{ a.time_created | natural_time }}
                    {% if not a.deleted %}
                    <a href="{{ url_for('brother.appendix_process', aid=a.id, next=request.url, process='del')}}" class="label-danger label pull-right">{{ _('Delete') }}</a>
                    {% elif a.deleted and a.append_deleted %}
                    <a href="{{ url_for('brother.appendix_process', aid=a.id, next=request.url, process='active')}}" class="label-success label pull-right">{{ _('Activate') }}</a>
                    {% endif %}
                </p>
            <div>
            {{a.content_rendered | safe}}
            </div>
            </div>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="panel panel-default">
    <div class="panel-heading">
    <p class="panel-title">
        {% if topic.reply_count %}
        {{ topic.reply_count }} {{ _('reply') }}
        {% else %}
        {{ _('no replies yet') }}
        {% endif %}
    </p>
    </div>
    {% if topic.reply_count %}
    <ul class="list-group">
        {% for c in comments %}
            {% if c.deleted and not c.comment_deleted %}
            <div class="list-group-item list-topic-item blocked">
                <div class="glyphicon glyphicon-ban-circle fa-3x watermark"></div>
            {% else %}
            <div class="list-group-item list-topic-item">
            {% endif %}
                <div class="row">
                    <a href="{{ url_for('user.info', uid=c.user_id) }}" class="col-md-1"><img title="{{c.user().username}}" class="avatar-middle" src=" {{ c.user().avatar_url }} "></a>
                    <div class="col-xs-11">
                        <div class="row">
                            <div class="reply-author col-sm-10">
                                <a href="{{ url_for('brother.user_more', uid=c.user_id) }}">{{c.user().username}}</a>
                                <span class="list-time">{{c.time_created | natural_time}}</span>

                            </div>
                            <div class="col-sm-2">
                                {% if not c.deleted%}
                                <a href="{{ url_for('brother.comment_process', cid=c.id, next=request.url, process='del')}}" class="label-danger label pull-right">{{ _('Delete') }}</a>
                                {% elif c.deleted and c.comment_deleted %}
                                <a href="{{ url_for('brother.comment_process', cid=c.id, next=request.url, process='active')}}" class="label-success label pull-right">{{ _('Activate') }}</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="reply-content col-md-11" style="margin-top:0.8em">
                                {{c.content_rendered | safe}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    <div class="panel-footer">
        {{ pagination.links }}
    </div>
    {% endif %}
    </ul>
</div>

{% endblock %}