nahan/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 10:15:12

from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config


mail = Mail()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .user import user as user_blueprint
    app.register_blueprint(user_blueprint, url_prefix='/user')
    from .voice import voice as voice_blueprint
    app.register_blueprint(voice_blueprint)
    from .brother import brother as brother_blueprint
    app.register_blueprint(brother_blueprint)
    return app

nahan/brother/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-18 21:33:24

from flask import Blueprint
brother = Blueprint('brother', __name__)
from . import views

nahan/brother/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-09-08 18:06:32

from flask import render_template, redirect, request, url_for, abort, current_app, jsonify
from flask_login import login_user, logout_user, current_user
from flask_babel import gettext
from functools import wraps
from flask_paginate import Pagination
from ..util import natural_time
from ..models import User, Topic, Node, Comment, TopicAppend
from . import brother
from .. import db


def superuser_login(func):
    @wraps(func)
    def wrap(*args, **kwargs):
        if current_user.is_authenticated and current_user.is_superuser:
            return func(*args, **kwargs)
        else:
            return redirect(url_for('brother.auth', next=request.url))
    return wrap


@brother.route("/admin/", methods=['GET', 'POST'])
def auth():
    if request.method == 'GET':
        if current_user.is_authenticated and current_user.is_superuser:
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        return render_template("brother/auth.html", form=None)
    elif request.method == 'POST':
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()
        if u and u.verify_password(_form['password']) and u.is_superuser:
            login_user(u)
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        else:
            message = gettext('Invalid username or password.')
            return render_template('brother/auth.html', form=_form, message=message)


@brother.route("/admin/signout/")
@superuser_login
def signout():
    logout_user()
    return redirect(url_for('brother.auth'))


@brother.route("/admin/topics/")
@superuser_login
def topic_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/topic.html', title=gettext('Normal Topics'))
        elif classify == 'deleted':
            return render_template('brother/topic_deleted.html', title=gettext('Deleted Topics'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/comments/")
@superuser_login
def comment_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/comment.html', title=gettext('Normal Comments'))
        elif classify == 'deleted':
            return render_template('brother/comment_deleted.html', title=gettext('Deleted Comments'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/nodes/")
@superuser_login
def node_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/node.html', title=gettext('Normal Nodes'))
        elif classify == 'deleted':
            return render_template('brother/node_deleted.html', title=gettext('Deleted Nodes'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/users/")
@superuser_login
def user_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/user.html', title=gettext('Normal Users'))
        elif classify == 'deleted':
            return render_template('brother/user_deleted.html', title=gettext('Blacklist Users'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/topic/<int:tid>/")
@superuser_login
def topic_more(tid):
    """ Delete part or all of one topic.

    Can delete either one or more comment, appendix or the whole topic.
    """
    t = Topic.query.filter_by(id=tid).first_or_404()
    if request.method == 'GET':
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        all_comments = t.extract_comments()
        comments = all_comments[offset:offset + per_page]
        pagination = Pagination(page=page, total=len(all_comments),
                                per_page=per_page,
                                record_name='comments',
                                CSS_FRAMEWORK='bootstrap',
                                bs_version=3)

        return render_template('brother/topic_more.html',
                               title=gettext('More About Topic'),
                               topic=t,
                               comments=comments,
                               pagination=pagination)
    else:
        abort(404)


@brother.route("/admin/node/<int:nid>/", methods=['GET', 'POST'])
@superuser_login
def node_more(nid):
    """ Update the title and description of node despite of node is deleted or not.
    """
    n = Node.query.filter_by(id=nid).first_or_404()
    if request.method == 'GET':
        return render_template('brother/node_more.html',
                               title=gettext('More About Node'),
                               node=n)
    elif request.method == 'POST':
        n.title = request.form['title']
        n.description = request.form['description']
        db.session.commit()
        return redirect(url_for('brother.node_manage', classify="normal"))
    else:
        abort(404)


@brother.route("/admin/user/<int:uid>/")
@superuser_login
def user_more(uid):
    content = request.args['content']
    if content not in ['Topic', 'Comment']:
        abort(404)

    if request.method == 'GET':
        u = User.query.filter_by(id=uid).first_or_404()
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        if content == 'Topic':
            all_topics = u.extract_topics()
            topics = all_topics[offset:offset + per_page]
            pagination_topic = Pagination(page=page, total=len(all_topics),
                                          per_page=per_page,
                                          record_name='topics',
                                          CSS_FRAMEWORK='bootstrap',
                                          bs_version=3)
            return render_template('brother/user_more_topic.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   topics=topics,
                                   pagination_topic=pagination_topic)
        else:
            all_comments = u.extract_comments()
            comments = all_comments[offset:offset + per_page]
            pagination_comment = Pagination(page=page, total=len(all_comments),
                                            per_page=per_page,
                                            record_name='comments',
                                            CSS_FRAMEWORK='bootstrap',
                                            bs_version=3)
            return render_template('brother/user_more_comment.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   comments=comments,
                                   pagination_comment=pagination_comment)
    else:
        abort(404)


@brother.route("/admin/topics/list/")
@superuser_login
def topic_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'reply_count', 'username', 'node_title']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    topics = Topic.query.filter_by(deleted=status).all()
    map(lambda x: setattr(x, 'username', x.user().username), topics)
    map(lambda x: setattr(x, 'node_title', x.node().title), topics)

    # Filter the topic according to the keywords.
    key = request.args.get('sSearch')
    if key:
        topics = list(filter(lambda x: (key == str(x.id) or key == str(x.reply_count) or key in x.title or
                                        key in x.username or key in x.node_title), topics))

    # Sort the data according to specified columns.
    topics.sort(key=lambda x: getattr(x, fields[order_field]), reverse=False if order_dir == 'asc' else True)

    # Put data together to response.
    data = dict()
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(topics)
    data['iTotalRecords'] = Topic.query.count()

    topics = topics[start:start + length]
    map(lambda x: setattr(x, 'more',
                          '<a href="%s" class="label label-success">%s</a>' %
                          (url_for('brother.topic_more', tid=x.id), gettext('more'))), topics)
    data['aaData'] = [[t.id, t.title, t.reply_count, t.username, t.node_title, t.more] for t in topics]

    return jsonify(**data)


@brother.route("/admin/nodes/list/")
@superuser_login
def node_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'description', 'count']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    nodes = Node.query.filter_by(deleted=status).all()
    # Filter the users according to the keywords.
    key = request.args.get('sSearch')

    map(lambda x: setattr(x, 'count', 0 if not x.topics else len(x.topics.split(","))), nodes)
    if key:
        nodes = list(filter(lambda x: (key == str(x.id) or key in x.title or

nahan/user/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-06-30 21:55:44

from flask import Blueprint
user = Blueprint('user', __name__)
from . import views

nahan/voice/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 09:44:05


from flask import Blueprint
voice = Blueprint('voice', __name__)
from . import views

nahan/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=360, initial-scale=0.75 user-scalable=no">
        {% block header_ext%}
        {% endblock %}
        <title>
            {% block title %}{% if title %}{{ title }}{% endif %}-{{_('Speaker for children')}}{% endblock %}
        </title>

        <!-- Bootstrap -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('voice.index') }}">{{_('Index')}}</a>
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('voice.hot') }}">{{ _('Hottest Topics') }}</a></li>
                        <li><a href="{{ url_for('voice.all_nodes') }}">{{ _('All Nodes') }}</a></li>
                    </ul>

                    {% if current_user.is_authenticated %}
                    <div class="navbar-form navbar-right">
                        <a class="btn btn-info" id="new-btn" href=" {{url_for('voice.create')}}">
                            {{ _('New Topic') }}
                        </a>
                    </div>
                    {% else %}
                    <div class="navbar-form navbar-right">
                        <ul class="nav navbar-nav">
                        <li class="dropdown">
                          <button type="button" class="btn btn-info btn-primary dropdown-toggle" data-toggle="dropdown">
                            {{ _('Sign In?') }}  <b class="caret"></b>
                          </button>
                            <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.signin') }}">{{ _('Sign In?') }} </a></li>
                            <li><a href="{{ url_for('user.reg') }}">{{_('Register Account') }}?</a></li>
                            <li><a href="{{ url_for('user.password_reset_request') }}">{{ _('Forget Password?') }}</a></li>
                            </ul>
                        </li>
                        </ul>
                    </div>
                    {% endif %}

                    <div class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input onkeydown="if(event.keyCode==13){search();}" type="text" id="search" class="form-control" name="search" placeholder="{{ _('Enter Key Words') }}">
                        </div>
                        <a class="btn btn-default" id="search-btn">
                            {{ _('Search') }}
                        </a>
                    </div>
                </div>
            </div><!--end nav container-->
        </nav><!--end nav-->

        <div id="wrap">
            <div class="container" id="main">
                <div class="row">
                    {% block inside_row %}
                    {% endblock %}
                </div><!--end outter row-->
            </div><!--end main-->
        </div><!--end wrap-->

        <footer id="footer">
            <div class="container clearfix">
                <p class="muted credit pull-right"> {{ _('copyright by xuezaigds@gmail.com') }}
                </p>
            </div>
        </footer>

        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/search.js') }}"></script>
        {% block footer_ext %}{% endblock %}
    </body>
</html>

nahan/templates/base_admin.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block header_ext%}
    {% endblock %}
    <title>{% if title %}{{ title }}{% endif %}-{{ _('admin') }}-{{ _("sitename") }}</title>

    <!-- Core CSS - Include with every page -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/select.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/buttons.dataTables.min.css') }}" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand">{{ _('Admin Management')}}</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle">{{ _('User')}}</a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('brother.user_manage', classify='normal') }}"> {{ _('Normal Users') }} </a></li>
                            <li><a href="{{ url_for('brother.user_manage', classify='deleted') }}"> {{ _('Blacklist Users') }}</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle">{{ _('Topic')}}</a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('brother.topic_manage', classify='normal') }}"> {{ _('Normal Topics') }} </a></li>
                            <li><a href="{{ url_for('brother.topic_manage', classify='deleted') }}"> {{ _('Deleted Topics') }}</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle">{{ _('Comment')}}</a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('brother.comment_manage', classify='normal') }}"> {{ _('Normal Comment') }} </a></li>
                            <li><a href="{{ url_for('brother.comment_manage', classify='deleted') }}"> {{ _('Blacklist Comment') }}</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle"}}>{{ _('Node')}}</a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('brother.node_manage', classify='normal') }}"> {{ _('Normal Nodes') }} </a></li>
                            <li><a href="{{ url_for('brother.node_manage', classify='deleted') }}"> {{ _('Deleted Nodes') }}</a></li>
                            <li><a href="{{ url_for('brother.node_create') }}"> {{ _('Create Node') }}</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="navbar-form navbar-right">
                    <a class="btn btn-info" id="new-btn" href="{{url_for('brother.signout')}}">
                        {{ _('Log Out') }}
                    </a>
                </div>
            </div>
        </div><!--end nav container-->
    </nav><!--end nav-->

    <div id="wrap">
        <div class="container" id="main">
            <div class="col-md-10 col-md-offset-1">
            {% block main %}
            {% endblock %}
            </div>
        </div><!--end main-->
    </div><!--end wrap-->
    <!-- Core Scripts - Include with every page -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/dataTables.select.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/dataTables.buttons.min.js') }}"></script>
    {% block footer_ext %}{% endblock %}
</body>

</html>

nahan/templates/base_with_sidebar.html
{% extends 'base.html' %}
{% block inside_row %}
<div class="col-md-3" id="left">
    {% block left %}{% endblock %}
</div>
<!--left: user info-->
<div class="col-md-8" id="right">
    {% block right %}{% endblock %}
</div>
<!--right: topics-->
{% endblock %}