nahan/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 10:15:12

from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config


mail = Mail()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .user import user as user_blueprint
    app.register_blueprint(user_blueprint, url_prefix='/user')
    from .voice import voice as voice_blueprint
    app.register_blueprint(voice_blueprint)
    from .brother import brother as brother_blueprint
    app.register_blueprint(brother_blueprint)
    return app

nahan/brother/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-18 21:33:24

from flask import Blueprint
brother = Blueprint('brother', __name__)
from . import views

nahan/brother/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-09-08 18:06:32

from flask import render_template, redirect, request, url_for, abort, current_app, jsonify
from flask_login import login_user, logout_user, current_user
from flask_babel import gettext
from functools import wraps
from flask_paginate import Pagination
from ..util import natural_time
from ..models import User, Topic, Node, Comment, TopicAppend
from . import brother
from .. import db


def superuser_login(func):
    @wraps(func)
    def wrap(*args, **kwargs):
        if current_user.is_authenticated and current_user.is_superuser:
            return func(*args, **kwargs)
        else:
            return redirect(url_for('brother.auth', next=request.url))
    return wrap


@brother.route("/admin/", methods=['GET', 'POST'])
def auth():
    if request.method == 'GET':
        if current_user.is_authenticated and current_user.is_superuser:
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        return render_template("brother/auth.html", form=None)
    elif request.method == 'POST':
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()
        if u and u.verify_password(_form['password']) and u.is_superuser:
            login_user(u)
            return redirect(request.args.get('next') or url_for('brother.user_manage', classify="normal"))
        else:
            message = gettext('Invalid username or password.')
            return render_template('brother/auth.html', form=_form, message=message)


@brother.route("/admin/signout/")
@superuser_login
def signout():
    logout_user()
    return redirect(url_for('brother.auth'))


@brother.route("/admin/topics/")
@superuser_login
def topic_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/topic.html', title=gettext('Normal Topics'))
        elif classify == 'deleted':
            return render_template('brother/topic_deleted.html', title=gettext('Deleted Topics'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/comments/")
@superuser_login
def comment_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/comment.html', title=gettext('Normal Comments'))
        elif classify == 'deleted':
            return render_template('brother/comment_deleted.html', title=gettext('Deleted Comments'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/nodes/")
@superuser_login
def node_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/node.html', title=gettext('Normal Nodes'))
        elif classify == 'deleted':
            return render_template('brother/node_deleted.html', title=gettext('Deleted Nodes'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/users/")
@superuser_login
def user_manage():
    if request.method == 'GET':
        classify = request.args['classify']
        if classify == 'normal':
            return render_template('brother/user.html', title=gettext('Normal Users'))
        elif classify == 'deleted':
            return render_template('brother/user_deleted.html', title=gettext('Blacklist Users'))
        else:
            abort(404)
    else:
        abort(404)


@brother.route("/admin/topic/<int:tid>/")
@superuser_login
def topic_more(tid):
    """ Delete part or all of one topic.

    Can delete either one or more comment, appendix or the whole topic.
    """
    t = Topic.query.filter_by(id=tid).first_or_404()
    if request.method == 'GET':
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        all_comments = t.extract_comments()
        comments = all_comments[offset:offset + per_page]
        pagination = Pagination(page=page, total=len(all_comments),
                                per_page=per_page,
                                record_name='comments',
                                CSS_FRAMEWORK='bootstrap',
                                bs_version=3)

        return render_template('brother/topic_more.html',
                               title=gettext('More About Topic'),
                               topic=t,
                               comments=comments,
                               pagination=pagination)
    else:
        abort(404)


@brother.route("/admin/node/<int:nid>/", methods=['GET', 'POST'])
@superuser_login
def node_more(nid):
    """ Update the title and description of node despite of node is deleted or not.
    """
    n = Node.query.filter_by(id=nid).first_or_404()
    if request.method == 'GET':
        return render_template('brother/node_more.html',
                               title=gettext('More About Node'),
                               node=n)
    elif request.method == 'POST':
        n.title = request.form['title']
        n.description = request.form['description']
        db.session.commit()
        return redirect(url_for('brother.node_manage', classify="normal"))
    else:
        abort(404)


@brother.route("/admin/user/<int:uid>/")
@superuser_login
def user_more(uid):
    content = request.args['content']
    if content not in ['Topic', 'Comment']:
        abort(404)

    if request.method == 'GET':
        u = User.query.filter_by(id=uid).first_or_404()
        per_page = current_app.config['PER_PAGE']
        page = int(request.args.get('page', 1))
        offset = (page - 1) * per_page

        if content == 'Topic':
            all_topics = u.extract_topics()
            topics = all_topics[offset:offset + per_page]
            pagination_topic = Pagination(page=page, total=len(all_topics),
                                          per_page=per_page,
                                          record_name='topics',
                                          CSS_FRAMEWORK='bootstrap',
                                          bs_version=3)
            return render_template('brother/user_more_topic.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   topics=topics,
                                   pagination_topic=pagination_topic)
        else:
            all_comments = u.extract_comments()
            comments = all_comments[offset:offset + per_page]
            pagination_comment = Pagination(page=page, total=len(all_comments),
                                            per_page=per_page,
                                            record_name='comments',
                                            CSS_FRAMEWORK='bootstrap',
                                            bs_version=3)
            return render_template('brother/user_more_comment.html',
                                   title=gettext('More About User'),
                                   user=u,
                                   comments=comments,
                                   pagination_comment=pagination_comment)
    else:
        abort(404)


@brother.route("/admin/topics/list/")
@superuser_login
def topic_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'reply_count', 'username', 'node_title']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    topics = Topic.query.filter_by(deleted=status).all()
    map(lambda x: setattr(x, 'username', x.user().username), topics)
    map(lambda x: setattr(x, 'node_title', x.node().title), topics)

    # Filter the topic according to the keywords.
    key = request.args.get('sSearch')
    if key:
        topics = list(filter(lambda x: (key == str(x.id) or key == str(x.reply_count) or key in x.title or
                                        key in x.username or key in x.node_title), topics))

    # Sort the data according to specified columns.
    topics.sort(key=lambda x: getattr(x, fields[order_field]), reverse=False if order_dir == 'asc' else True)

    # Put data together to response.
    data = dict()
    data['aaData'] = []
    data['iTotalDisplayRecords'] = len(topics)
    data['iTotalRecords'] = Topic.query.count()

    topics = topics[start:start + length]
    map(lambda x: setattr(x, 'more',
                          '<a href="%s" class="label label-success">%s</a>' %
                          (url_for('brother.topic_more', tid=x.id), gettext('more'))), topics)
    data['aaData'] = [[t.id, t.title, t.reply_count, t.username, t.node_title, t.more] for t in topics]

    return jsonify(**data)


@brother.route("/admin/nodes/list/")
@superuser_login
def node_table_list():
    deleted = request.args.get('deleted')
    if deleted not in ["True", "False"]:
        abort(404)
    status = True if deleted == "True" else False

    fields = ['id', 'title', 'description', 'count']
    order_dir = request.args.get('sSortDir_0')
    order_field = int(request.args.get('iSortCol_0'))
    length = int(request.args.get('iDisplayLength', 10))
    start = int(request.args.get('iDisplayStart', 0))

    nodes = Node.query.filter_by(deleted=status).all()
    # Filter the users according to the keywords.
    key = request.args.get('sSearch')

    map(lambda x: setattr(x, 'count', 0 if not x.topics else len(x.topics.split(","))), nodes)
    if key:
        nodes = list(filter(lambda x: (key == str(x.id) or key in x.title or

nahan/user/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-06-30 21:55:44

from flask import Blueprint
user = Blueprint('user', __name__)
from . import views

nahan/voice/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-07-01 09:44:05


from flask import Blueprint
voice = Blueprint('voice', __name__)
from . import views

nahan/templates/user/info.html
{% extends 'base_with_sidebar.html' %}
{% block left %}
{% include 'user/panel.html' %}
{% endblock %}

{% block right %}
<div class="panel panel-default">
    <div class="panel-body row">
        <div class="col-xs-2">
            <img class="avatar-large" src="{{ user.avatar_url }}" title="{{user.username}}"/>
        </div>
        <div class="col-xs-10">
            <p class="list-post-title"><strong>@{{user.username}} </strong></p>
            <p class="list-meta">{{ _('The') }} {{user.id}} {{ _('th users') }}, {{user.date_joined | natural_time}}{{ _(' join.') }}</p>
            {% if user.website %}
            <p class="list-meta"> {{ _('Personal website: ') }}
            <a target="_blank" href="{{user.website}}">{{user.website}}</a>
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% include 'voice/list.html' %}
{% endblock %}

nahan/templates/user/notify.html
{% extends 'base_with_sidebar.html' %}
{% block left %}
{% include 'user/panel.html' %}
{% endblock %}

{% block right %}
<div class="panel panel-default">
    {% if new %}
    <div class="panel-heading">
        <p class="panel-title">
            {{ _('Unread Mentions') }}
        </p>
    </div>
    <ul class="list-group">
        {% for n in new %}
        {% if not n.deleted %}
        <div class="list-group-item list-topic-item">
            <div class="row">
                <a href="{{ url_for('user.info', uid = n.sender_id) }}" class="col-xs-1"><img title="{{n.sender.username}}" class="avatar-middle" src="{{n.sender.avatar_url}}"></a>
                <div class="col-xs-10">
                    <div class="reply-author">
                        <a href="{{ url_for('user.info', uid = n.sender_id) }}">{{n.sender.username}}</a>
                        <span class="list-time">{{n.time_created | natural_time}}</span>
                    </div>
                    <div class="reply-content">
                        {% if n.comment_id %}
                        {{ _('In comment') }}
                        <a href="{{ url_for('voice.view', tid = n.topic_id) }}#comment-{{n.comment_id}}" > {{n.topic.title}}</a>
                        {% elif n.append_id %}
                        {{ _('In appendix') }}
                        <a href="{{ url_for('voice.view', tid = n.topic_id) }}#append-{{n.append_id}}" > {{n.topic.title}}</a>
                        {% else %}
                        {{ _('In topic') }}
                        <a href="{{ url_for('voice.view', tid= n.topic_id) }}" > {{n.topic.title}}</a>
                        {% endif %}
                        {{ _('Mentioned you') }}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
    {% if old %}
    <div class="panel-heading">
        <p class="panel-title">
            {{ _('Old Mentions') }}
        </p>
    </div>
    <ul class="list-group">
        {% for n in old %}
        {% if not n.deleted %}
        <div class="list-group-item list-topic-item">
            <div class="row ">
                <a href="{{ url_for('user.info', uid = n.sender_id) }}" class="col-xs-1"><img title="{{n.sender.username}}" class="avatar-middle" src="{{n.sender.avatar_url }}"></a>
                <div class="col-xs-10">
                    <div class="reply-author">
                        <a href="{{ url_for('user.info', uid = n.sender_id) }}">{{ n.sender.username }}</a>
                        <span class="list-time">{{ n.time_created | natural_time }}</span>
                    </div>
                    <div class="reply-content">
                        {% if n.comment_id %}
                        {{ _('In comment') }}
                        <a href="{{ url_for('voice.view', tid=n.topic_id) }}#comment-{{n.comment_id}}" > {{n.topic.title}}</a>
                        {% elif n.append_id %}
                        {{ _('In appendix') }}
                        <a href="{{ url_for('voice.view', tid = n.topic_id) }}#append-{{n.append_id}}" > {{n.topic.title}}</a>
                        {% else %}
                        {{ _('In topic') }}
                        <a href="{{ url_for('voice.view', tid=n.topic_id) }}" > {{n.topic.title}}</a>
                        {% endif %}
                        {{ _('Mentioned you') }}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
    {% if not old and not new %}
        <div class="panel-heading">
        <p class="panel-title">
            {{ _('No Mentions') }}
        </p>
    </div>
    {% endif %}
</div>

{% endblock %}

nahan/templates/user/panel.html
<div class="panel panel-default">
    <div class="panel-body">
        {% if current_user.is_authenticated %}
        <div class="row">
            <a class="col-xs-4"><img title="{{current_user.username}}" class="avatar-large" src="{{current_user.avatar_url}}"></a>
            <div class="col-xs-8">
            <p class="list-post-title"><strong>{{current_user.username}}</strong></p>
            <p class="list-meta" style="margin-top: 1em">
            {{ _('The ')}}{{ current_user.id }}{{ _('th users') }}
            </p>
        </div>
        </div>
        <div class="row" style="margin-top: 1em">
            <div class="col-xs-4">
                <a href="{{ url_for('user.info', uid=current_user.id) }}" class="btn btn-block"> <span class="glyphicon glyphicon-home"></span> {{ _('info') }} </a>
            </div>
            <div class="col-xs-4">
                <a href="{{ url_for('user.setting_info') }}" class="btn btn-block"> <span class="glyphicon glyphicon-cog"></span> {{ _('settings') }} </a>
            </div>
            <div class="col-xs-4">
                <a href="{{ url_for('user.signout') }}" class="btn btn-block"> <span class="glyphicon glyphicon-log-out"></span> {{ _('log out') }} </a>
            </div>
        </div>
        {% else %}
        <p class="list-post-title text-center"><strong>{{  _('Speaker for children') }}</strong></p>
        <div class="row" style="margin: 1em 0 0 1em">
        <p class="list-meta">{{ _(' Do you ever SEE what children play.') }}</p>
        <p class="list-meta">{{ _(' Do you ever HEAR what children speak.') }}</p>
        <p class="list-meta">{{ _(' Do you ever Think what children think.') }}</p>
        </div>
        {% endif %}
    </div>
    {% if current_user.is_authenticated %}
        {% if current_user.extract_unread_notify() %}
        <div class="panel-footer">
            <span class="notification"><a href="{{ url_for('user.notify') }}">{{current_user.extract_unread_notify() | length }} {{ _('New Messages') }}</a></span>
        </div>
        {% else  %}
        <div class="panel-footer">
            <span class="notification"><a href="{{ url_for('user.notify') }}">{{ _('Site Messages') }}</a></span>
        </div>
        {% endif %}
    {% endif %}
</div>

nahan/templates/user/passwd_reset.html
{% extends 'base.html' %}
{% block title %}
{{ _('reset password') }}
{% endblock %}

{% block inside_row %}

<div class="panel panel-default col-md-6 col-md-offset-3">
    <form class="form-horizontal panel-body password-reset" method="post">
        <h2 class="text-center" style="margin-bottom:1em"> {{ _('reset password') }} </h2>

		<div class="form-group ">
			<label for="email"> {{ _('register email') }} </label>
            <input class="form-control" id="email" name="email" placeholder=example@gmail.com type="text">
            {% if message_email %}
            <div class="messages col-sm-10"> <p class="text-danger"> {{ message_email }} </p> </div>
            {% endif %}
        </div>

        <div class="form-group">
            <button class="btn btn-default btn-success pull-right">
                {{ _('submit') }}
            </button>
        </div>

    </form>
</div>
{% endblock %}

nahan/templates/user/passwd_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
{{ _('reset password confirm') }}
{% endblock %}

{% block inside_row %}

<div class="panel panel-default col-md-6 col-md-offset-3">
    <form class="form-horizontal panel-body password-reset" method="post">
        <h2 class="text-center" style="margin-bottom:1em"> {{ _('Enter new password') }} </h2>

        <div class="form-group ">
            <label for="password">{{ _('new password') }}</label>
            <input class="form-control" id="password" name="password" type="password">
        </div>

         <div class="form-group ">
            <label for="password">{{ _('repeat password') }}</label>
            <input class="form-control" id="password2" name="password2" type="password" >
             {% if message_p %} <div class="messages"> <p class="text-danger"> {{ message_p }} </p> </div> {% endif %}
        </div>

        <div class="form-group">
            <button class="btn btn-default btn-success pull-right">
                {{ _('Confirm') }}
            </button>
        </div>
    </form>
</div>
{% endblock %}

nahan/templates/user/passwd_reset_done.html
{% extends 'base.html' %}
{% block title %}{{ _("Password reset email sent") }}{% endblock %}

{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3 ">
    {% if 'Successful' == message %}
    <h2 class="text-center" style="margin-bottom:1em"> {{ _('Successful!') }} </h2>
    <p>
        {{ _("Password reset successfully.  You can jump to") }} <a href="{{url_for('voice.index') }}">index</a>
        {{ _("to see what's happened recently.") }}
        </br>
        </br>
        </br>
    </p>
    {% else %}
    <h2 class="text-center" style="margin-bottom:1em"> {{ _('Failed!') }} </h2>
    <p>
        {{ _('Password reset failed somehow.  Please make sure your reset link is legal and not used already!') }}
        </br>
        </br>
        </br>
    </p>
    {% endif %}

</div>
{% endblock %}

nahan/templates/user/passwd_reset_email.html
<p>{{ _('Dear') }} {{ user.username }}:</p>
<p>{{ _('To reset your password') }} <a href="{{ url_for('user.password_reset', token=token, _external=True) }}">{{ _('click here.') }}</a></p>
<p>{{ _("Alternatively, you can paste the following link in your browser's address bar:") }}</p>
<p>{{ url_for('user.password_reset', token=token, _external=True) }}</p>
<p>{{ _('If you have not requested a password reset simply ignore this message.') }}</p>
<p>{{ _('Sincerely, \n The NaHan Team') }} </p>
<p class="text-info">{{ _('Note: replies to this email address are not monitored.') }}</small></p>

nahan/templates/user/passwd_reset_sent.html
{% extends 'base.html' %}
{% block title %}{{ _("Password reset email sent") }}{% endblock %}

{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3 ">
    <h2 class="text-center" style="margin-bottom:1em"> {{ _('Email Sent') }} </h2>
    <p>
        {{ _('We have sent you an email with a link to reset your password. Please check your email and click the link to continue.') }}
        </br>
        </br>
        </br>
    </p>
</div>
{% endblock %}

nahan/templates/user/reg.html
{% extends 'base.html' %}
{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3">
    <form class="panel-body" role="form" method="post" action="{{ url_for('user.reg')}}">
        <h2 class="text-center" style="margin-bottom:1em">{{ _('register a account') }}</h2>
        <div class="form-group ">
            <label for="username">{{ _('username') }}</label>
            <input class="form-control" id="username" name="username" placeholder="{{ _('letters,digits,underscore') }}" type="text" value="{{ form.username }}">
            {% if message_u %} <div class="messages"> <p class="text-danger"> {{ message_u }} </p> </div> {% endif %}
        </div>

        <div class="form-group ">
            <label for="email">{{ _('Email') }}</label>
            <input class="form-control" id="email" name="email" type="email" placeholder="" value="{{ form.email }}" >
            {% if message_e %} <div class="messages"> <p class="text-danger"> {{ message_e }} </p> </div> {% endif %}
        </div>

        <div class="form-group ">
            <label for="password">{{ _('password') }}</label>
            <input class="form-control" id="password" name="password" type="password" value="{{ form.password }}">
        </div>

         <div class="form-group ">
            <label for="password">{{ _('repeat password') }}</label>
            <input class="form-control" id="password2" name="password2" type="password" value="{{ form.password2 }}">
             {% if message_p %} <div class="messages"> <p class="text-danger"> {{ message_p }} </p> </div> {% endif %}
        </div>

        <div class="form-group">
            <button class="btn btn-success pull-right">
                {{ _('register') }}
            </button>
            <a class="btn btn-link pull-right" href="{{ url_for('user.signin')}}">{{ _('sign in?') }}</a>
        </div>
    </form>
</div>
{% endblock %}

nahan/templates/user/setting_avatar.html
{% extends 'base_with_sidebar.html' %}
{% block left %}
{% include 'user/panel.html' %}
{% endblock %}

{% block right %}
<div class="panel panel-default">
    <div class="panel-heading">
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('user.setting_info') }}"> {{_('Info')}}</a></li>
            <li><a href="{{ url_for('user.setting_password') }}"> {{ _('Password') }}</a></li>
            <li class="active"><a href="">{{ _('Avatar') }}</a></li>
        </ul>
    </div>

    {% if message_success %}
    </br>
    </br>
    <h2 class="text-center text-success" style="margin-bottom:1em"> {{ message_success }} </h2>
    </br>
    </br>

    {% else %}
    <form class="panel-body" method="post" action="" enctype="multipart/form-data">
        <div class="form-group col-md-8 col-md-offset-2">
            <label class="" for="avatar">{{ _('upload new avatar') }}</label>
            <input type="file" name="file" id="avatar" style="margin-top:1em">
            <label style="margin-top:1em">{{ _('maximum 512K, png and jpeg only') }}</label>
        </div>
        {% if message_fail %}
        <div class="form-group col-md-8 col-md-offset-2">
            <label class="text-center text-danger" style="margin-bottom:1em"> {{ message_fail }} </label>
        </div>
        {% endif %}
        <div class="form-group col-md-8 col-md-offset-2">
            <button class="btn btn-success pull-right">
                {{ _('update') }}
            </button>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

nahan/templates/user/setting_info.html
{% extends 'base_with_sidebar.html' %}

{% block left %}
{% include 'user/panel.html' %}
{% endblock %}

{% block right %}

<div class="panel panel-default">
    <div class="panel-heading">
        <ul class="nav nav-tabs">
            <li class="active"><a href="">{{ _('Info') }}</a></li>
            <li><a href="{{ url_for('user.setting_password') }}">{{ _('Password') }}</a></li>
            <li><a href="{{ url_for('user.setting_avatar') }}">{{ _('Avatar') }}</a></li>
        </ul>
    </div>

    {% if message_success %}
    </br>
    </br>
    <h2 class="text-center text-success" style="margin-bottom:1em"> {{ message_success }} </h2>
    </br>
    </br>

    {% else %}
    <form class="panel-body" method="post" action="">
        <div class="form-group col-md-8 col-md-offset-2">
            <label for="email"> {{ _('Email') }}</label>
            <input class="form-control" id="email" name="email" type="email" value="{{current_user.email}}">
            {% if message_email %}
            <div class="messages"> <p class="text-danger"> {{ message_email }} </p> </div>
            {% endif %}
        </div>
        <div class="form-group col-md-8 col-md-offset-2">
            <label for="website">{{ _('website') }}</label>
            <input class="form-control" id="website" name="website" type="url" {% if current_user.website %} value="{{ current_user.website }}" {% else%} placeholder="{{ _('Optional') }}" {%endif%}>
        </div>
        <div class="form-group col-md-8 col-md-offset-2">
            <button class="btn btn-success pull-right">
                {{ _('update') }}
            </button>
        </div>
    </form>
    {% endif %}
</div>

{% endblock %}

nahan/templates/user/setting_passwd.html
{% extends 'base_with_sidebar.html' %}
{% block left %}
{% include 'user/panel.html' %}
{% endblock %}
{% block right %}
<div class="panel panel-default">
        <div class="panel-heading">
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('user.setting_info') }}">{{ _('Info') }}</a></li>
            <li class="active"><a href="">{{ _('Password') }}</a></li>
            <li><a href="{{ url_for('user.setting_avatar') }}">{{ _('Avatar') }}</a></li>
        </ul>
    </div>

    {% if message_success %}
    </br>
    </br>
    <h2 class="text-center text-success" style="margin-bottom:1em"> {{ message_success }} </h2>
    </br>
    </br>

    {% else %}
    <form class="panel-body" method="post" action="">
        <div class="form-group col-md-8 col-md-offset-2">
            <label for="old_password">{{ _('current password') }}</label>
            <input class="form-control" id="old_password" name="old_password" type="password" value="{{ form.old_password}}">
            {% if message_cur %}
            <div class="messages"> <p class="text-danger"> {{ message_cur }} </p> </div>
            {% endif %}
        </div>
        <div class="form-group col-md-8 col-md-offset-2">
            <label for="password">{{ _('new password') }}</label>
            <input class="form-control" id="password" name="password" type="password" value="{{ form.password }}">
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
            <label for="password2">{{ _('repeat password') }}</label>
            <input class="form-control" id="password2" name="password2" type="password" value="{{ form.password2 }}">
            {% if message_new %}
            <div class="messages"> <p class="text-danger"> {{ message_new }} </p> </div>
            {% endif %}
        </div>
        <div class="form-group col-md-8 col-md-offset-2">
            <button class="btn btn-success pull-right">
                {{ _('update') }}
            </button>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}

nahan/templates/user/signin.html
{% extends 'base.html' %}
{% block inside_row %}
<div class="panel panel-default col-md-6 col-md-offset-3">

    <form class="panel-body" role="form" method="post" action="{{ url_for('user.signin', next=request.args.get('next')) }}">
        <h2 class="text-center" style="margin-bottom:1em"> {{ _('user sign in')}} </h2>
        {% if message %}
		<div class="messages"> <p class="text-danger"> {{ message }} </p></div>
		{% endif %}
        <div class="form-group ">
            <label for="email"> {{ _('email') }} </label>
            <input class="form-control" id="email" name="email" placeholder=example@gmail.com type="text", value="{{ form.email}}">
        </div>

        <div class="form-group ">
            <label for="password">{{_('password') }}</label>
            <input class="form-control" id="password" name="password" type="password", value="{{ form.password}}">
        </div>

        <div class="form-group">
            <button class="btn btn-default btn-success pull-right">
                {{ _('sign in') }}
            </button>
            <a class="btn btn-link pull-right" href="{{ url_for('user.reg') }}">{{ _('reg') }}</a>
            <a class="btn btn-link pull-right" href="{{ url_for('user.password_reset_request') }}">{{ _('forget password?') }}</a>
        </div>
    </form>
</div>
{% endblock %}